export const zhCN = {
  common: {
    open: '打开',
    opening: '正在打开…',
    close: '关闭',
    cancel: '取消',
    send: '发送',
    continue: '继续',
    decline: '拒绝',
    save: '保存',
    delete: '删除',
    remove: '移除',
    rename: '重命名',
    create: '创建',
    creating: '正在创建…',
    search: '搜索',
    clearSearch: '清除搜索',
    settings: '设置',
    loading: '加载中…',
    reload: '重新加载',
    retry: '重试',
    unavailable: '不可用',
    active: '当前使用',
    switch: '切换',
    switching: '正在切换…',
    account: '账号',
    review: '评审',
    untitledThread: '未命名线程',
    exportedAt: '导出时间',
    threadId: '线程 ID',
    attachments: '附件',
    images: '图片',
    noOutput: '（无输出）',
    chatRecord: '聊天记录',
  },
  sidebar: {
    expandSidebar: '展开侧边栏',
    collapseSidebar: '收起侧边栏',
    searchThreads: '搜索线程',
    filterThreads: '筛选线程…',
    skillsHub: '技能中心',
  },
  settings: {
    accounts: '账号',
    expandAccounts: '展开账号',
    collapseAccounts: '收起账号',
    requireCommandEnter: '需要按 ⌘ + Enter 才发送',
    busySendAs: '忙碌时发送为',
    appearance: '外观',
    chatWidth: '聊天宽度',
    clickToToggleDictation: '点击切换听写',
    autoSendDictation: '自动发送听写',
    githubTrendingProjects: 'GitHub 热门项目',
    provider: '提供方',
    customEndpointUrl: '自定义端点 URL',
    dictationLanguage: '听写语言',
    telegram: 'Telegram',
    botToken: 'Bot token',
    allowedTelegramUserIds: '允许的 Telegram 用户 ID',
    context: '上下文',
    buildLabel: '工作树名称和版本',
    openRouterApiKey: 'OpenRouter API key',
    getApiKey: '获取 API key',
    removeCustomKeyUseCommunity: '移除自定义 key，改用社区 key',
    customKeyPlaceholder: 'sk-or-v1-...（可选，留空则使用免费 key）',
    endpointPlaceholder: 'https://api.example.com/v1',
    bearerTokenPlaceholder: 'Bearer token（可选）',
    set: '设置',
    autoDetect: '自动检测',
    searchLanguage: '搜索语言…',
    telegramHelp: '每行填写一个 Telegram 用户 ID，或用逗号分隔。使用 `*` 表示允许所有 Telegram 用户。未授权用户会在拒绝消息里看到自己的 ID，方便复制到这里。',
    saveTelegramConfig: '保存 Telegram 配置',
    saving: '正在保存…',
  },
  theme: {
    system: '跟随系统',
    dark: '深色',
    light: '浅色',
  },
  newThread: {
    title: '开始构建',
    chooseFolder: '选择文件夹',
    quickSearchProject: '快速搜索项目',
    addNewProject: '+ 添加新项目',
    selectedFolder: '已选文件夹',
    selectFolder: '选择文件夹',
    currentFolder: '当前文件夹',
    unavailablePath: '不可用',
    showHiddenFolders: '显示隐藏文件夹',
    newFolder: '新建文件夹',
    folderName: '文件夹名称',
    filterFolders: '筛选文件夹…',
    loadingFolders: '正在加载文件夹…',
    noFoldersMatch: '没有文件夹匹配当前筛选条件。',
    noSubfoldersFound: '这里没有找到子文件夹。',
    baseBranch: '基础分支',
    selectBranch: '选择分支',
    searchBranches: '搜索分支…',
    loadingBranches: '正在加载分支…',
    noGitBranches: '当前文件夹没有可用的 Git 分支。',
    trendingGitHubProjects: 'GitHub 热门项目',
    loadingTrendingProjects: '正在加载热门项目…',
    trendingUnavailable: '当前无法获取热门仓库。',
    noDescription: '暂无描述。',
  },
  runtime: {
    localProject: '本地项目',
    newWorktree: '新建工作树',
  },
  review: {
    open: '评审（已打开）',
    closed: '评审',
    detachedHead: '游离 HEAD',
  },
  dictation: {
    preferred: '优先',
    autoDetect: '自动检测',
  },
  account: {
    runCodexLogin: '请先运行 `codex login`，然后点击重新加载。',
    workspace: '工作区',
    unavailable: '不可用',
    unavailableAccount: '不可用账号',
    removing: '正在移除…',
    removeConfirm: '再次点击以移除',
    weeklyRemaining: '本周剩余',
    unlimitedCredits: '无限额度',
    creditsSuffix: '额度',
    loadingQuota: '正在加载额度…',
    quotaUnavailable: '额度不可用',
    fetchingDetails: '正在获取账号详情…',
    loadAccountsFailed: '加载账号失败',
    refreshAccountsFailed: '刷新账号失败',
    switchAccountFailed: '切换账号失败',
    removeAccountFailed: '移除账号失败',
    finishTurnBeforeSwitch: '请先完成当前轮次并处理待处理请求，再切换账号。',
    finishTurnBeforeRemove: '请先完成当前轮次并处理待处理请求，再移除当前账号。',
  },
  telegram: {
    notConfigured: '未配置',
    online: '在线',
    configuredOffline: '已配置（离线）',
    allowAllUsers: '允许所有用户',
    allowedUsers: (count: number) => `允许 ${count} 个用户`,
    mapped: (chats: number, threads: number, allowlist: string) => `${chats} 个聊天，${threads} 个线程，${allowlist}`,
    errorPrefix: (message: string) => `，错误：${message}`,
    loadStatusFailed: '加载 Telegram 状态失败',
    loadConfigFailed: '加载 Telegram 配置失败',
    botTokenRequired: 'Telegram bot token 为必填项。',
    allowedUsersRequired: '至少需要填写一个允许的 Telegram 用户 ID，或填写 `*`。',
    configuredAlert: 'Telegram bot 已配置完成。只有在允许名单里的 Telegram 用户可以使用桥接功能。',
    connectFailed: '连接 Telegram bot 失败',
  },
  context: {
    waitingUsage: '正在等待该线程的 Codex token usage 事件。',
    modelWindow: (tokens: string) => `模型上下文窗口：${tokens} tokens`,
    currentUsage: (tokens: string) => `当前上下文用量：${tokens} tokens`,
    cumulativeUsage: (tokens: string) => `线程累计用量：${tokens} tokens`,
    remainingContext: (tokens: string) => `剩余上下文：${tokens} tokens`,
    modelWindowUnavailable: '最新 usage 事件里没有模型上下文窗口信息。',
    awaitingData: '等待数据',
    left: (tokens: string) => `${tokens} 剩余`,
    used: (tokens: string) => `${tokens} 已使用`,
    updatesAfterNextEvent: '将在下一次 token usage 事件后更新',
    windowUnavailable: '窗口大小不可用',
  },
  content: {
    skills: '技能',
    newThread: '新线程',
    chooseThread: '选择一个线程',
  },
  actions: {
    preferredLanguage: (label: string) => `优先：${label}`,
  },
  threadTree: {
    pin: '置顶',
    worktreeThread: '工作树线程',
    threadMenu: '线程菜单',
    threads: '线程',
    organizeThreads: '整理线程',
    organize: '整理方式',
    byProject: '按项目分组',
    chronologicalList: '按时间排序',
    noMatchingThreads: '没有匹配的线程',
    loadingThreads: '正在加载线程…',
    projectMenu: '项目菜单',
    editName: '编辑名称',
    projectName: '项目名称',
    noThreads: '暂无线程',
    showLess: '收起',
    showMore: '显示更多',
    browseFiles: '浏览文件',
    exportChat: '导出聊天',
    createChatFork: '创建聊天分支',
    renameThread: '重命名线程',
    deleteThread: '删除线程',
    threadTitle: '线程标题',
    makeShortAndRecognizable: '尽量简短，方便识别。',
    addTitle: '输入标题…',
    deleteThreadTitle: '删除线程',
    deleteThreadQuestion: '删除这个线程？',
    deleteThreadDescription: (title: string) => `这会归档线程“${title}”。稍后仍可在已归档线程中找到它。`,
    newThreadInProject: (projectName: string) => projectName ? `在 ${projectName} 中新建线程` : '新建线程',
    awaitingApproval: '等待批准',
    awaitingResponse: '等待回复',
  },
  dropdown: {
    noMatchingProjects: '没有匹配的项目',
    open: '打开',
    quickSearchProjects: '快速搜索项目',
    addNewProject: '添加新项目',
    projectNameOrPath: '项目名称或绝对路径',
    continueIn: '继续在此处进行',
    noResults: '没有结果',
    select: '请选择…',
    selectedCount: (count: number) => `已选择 ${count} 项`,
    searchSkills: '搜索技能…',
    noSkillsFound: '没有找到技能',
  },
  composer: {
    selectedImage: '已选图片',
    image: '图片',
    remove: (label: string) => `移除 ${label}`,
    removeFolder: (name: string) => `移除文件夹 ${name}`,
    removeSkill: (name: string) => `移除技能 ${name}`,
    dropImagesOrFiles: '拖放图片或文件到这里',
    noMatchingFiles: '没有匹配的文件',
    addPhotosAndFiles: '添加图片和文件',
    addFolder: '添加文件夹',
    takePhoto: '拍照',
    inProgressSend: '进行中发送方式',
    queue: '排队',
    steer: '引导',
    model: '模型',
    skills: '技能',
    thinking: '思考强度',
    planMode: '计划模式',
    planModeDescription: '助手会先给出计划再执行',
    fastMode: '快速模式',
    fastModeEnabled: '快速模式已启用',
    fastModeDisabled: '快速模式已禁用',
    savingSpeedSetting: '正在保存速度设置…',
    fasterSpeed: '速度约快 1.5 倍，额度按 2 倍消耗',
    defaultSpeed: '默认速度，正常消耗额度',
    stopDictation: '停止听写',
    clickToDictate: '点击开始听写',
    holdToDictate: '按住开始听写',
    noSpeechClickAgain: '没有检测到语音。说完后再点击一次。',
    noSpeechHoldAndSpeak: '没有检测到语音。按住麦克风并说话。',
    microphoneDenied: '麦克风权限被拒绝。',
    dictationFailed: '听写失败。',
    stopUnavailableWhileSaving: '线程保存完成后才能停止',
    stop: '停止',
    queueMessage: '加入队列',
    sendMessage: '发送消息',
    send: '发送',
    sendAs: (mode: string) => `发送方式：${mode}`,
    attachingProgress: (count: number) => count === 1 ? '正在附加文件…' : `正在附加 ${count} 个文件…`,
    attachFailedProgress: (failed: number, remainingLabel: string) => `${failed} 个失败，正在附加 ${remainingLabel}…`,
    attachedAndFailed: (succeeded: number, failed: number) => `已附加 ${succeeded} 个，失败 ${failed} 个。`,
    couldNotAttach: (failed: number) => failed === 1 ? '无法附加文件。' : `无法附加 ${failed} 个文件。`,
    fileCount: (count: number) => count === 1 ? '1 个文件' : `${count} 个文件`,
    folderFileCount: (count: number) => count === 1 ? '1 个文件' : `${count} 个文件`,
    uploadingProgress: (percent: number, processed: number, total: number) => `${percent}% 上传中（${processed}/${total}）`,
    selectThreadToSend: '先选择一个线程再发送消息',
    loadingModelsForPlanMode: '正在为计划模式加载模型…',
    typeMessage: '输入消息…（`@` 选择文件，`/` 选择技能）',
    planEducation: '教育版',
    resettingNow: '正在重置',
    resetsIn: (value: number, unit: string) => `${value}${unit} 后重置`,
    unlimitedCredits: '无限额度',
    credits: (value: string) => `额度：${value}`,
    primaryWindow: (summary: string, reset: string) => `主要窗口：${summary}${reset ? `，${reset}` : ''}`,
    secondaryWindow: (summary: string, reset: string) => `次要窗口：${summary}${reset ? `，${reset}` : ''}`,
    creditsUnlimited: '额度：无限',
    weeklyRefresh: (date: string) => `每周刷新：${date}`,
    contextWindow: (percentRemaining: number, percentUsed: number) => `上下文窗口：剩余 ${percentRemaining}%（已用 ${percentUsed}%）`,
    inContext: (used: string, total: string) => `上下文内：${used} / ${total} tokens`,
  },
  pendingRequest: {
    approvalChoices: '批准选项',
    noAndTellCodex: '不同意，并告诉 Codex 该如何调整',
    skip: '跳过',
    pendingCount: (count: number) => `${count} 个待处理`,
    server: '服务器',
    openAuthorizationLink: '打开授权链接',
    value: '值',
    choice: '选项',
    selectTrueOrFalse: '请选择是或否',
    true: '是',
    false: '否',
    selectAnOption: '选择一个选项',
    otherAnswer: '其他回答',
    failToolCall: '标记工具调用失败',
    successEmpty: '成功（空结果）',
    returnEmptyResult: '返回空结果',
    rejectRequest: '拒绝请求',
    awaitingApproval: '等待批准',
    mcpInputRequired: 'MCP 服务器需要输入',
    awaitingResponse: '等待回复',
    toolCallWaiting: '工具调用等待回复',
    runThisCommand: '要运行这条命令吗？',
    makeTheseChanges: '要应用这些更改吗？',
    grantThesePermissions: '要授予这些权限吗？',
    mcpNeedsInput: 'MCP 服务器需要你的输入，Codex 才能继续。',
    codexNeedsAnswer: 'Codex 需要你的回答后才能继续。',
    codexWaitingForResponse: 'Codex 正在等待回复后继续。',
    read: (paths: string) => `读取：${paths}`,
    write: (paths: string) => `写入：${paths}`,
    networkAccess: '网络访问',
    yes: '同意',
    yesForSession: '本会话同意',
    answerRequiredField: (label: string) => `请填写必填字段：${label}。`,
    answerRequiredFields: (labels: string) => `请填写必填字段：${labels}。`,
    cancelledFromCodexUi: '已从 CodexUI 取消。',
    declinedFromCodexUi: '已从 CodexUI 拒绝。',
    toolCallRejected: '工具调用已被 CodexUI 拒绝。',
    rejectedFromCodexUi: '请求已被 CodexUI 拒绝。',
  },
  skills: {
    disabled: '已禁用',
    installed: '已安装',
    browseFiles: '浏览文件',
    close: '关闭',
    loadingSkillContents: '正在加载技能内容…',
    viewOnGitHub: '在 GitHub 上查看',
    uninstalling: '正在卸载…',
    uninstall: '卸载',
    installing: '正在安装…',
    install: '安装',
    disable: '禁用',
    enable: '启用',
    hubTitle: '技能中心',
    hubSubtitle: '浏览并发现 OpenClaw 社区里的技能',
    syncTitle: '技能同步（GitHub）',
    connectedRepo: (owner: string, repo: string) => `已连接：${owner}/${repo}`,
    loggedInAs: (username: string) => `已登录：${username}`,
    notConnected: '未连接',
    startup: (mode: string) => `启动：${mode}`,
    branch: (branch: string) => `分支：${branch}`,
    action: (action: string) => `操作：${action}`,
    manualSync: (status: string) => `手动同步：${status}`,
    openDeviceLogin: '打开 GitHub 设备登录并输入代码：',
    loginWithGitHub: '使用 GitHub 登录',
    deviceLogin: '设备登录',
    logoutGitHub: '退出 GitHub',
    syncing: '同步中…',
    startupSync: '启动同步',
    pulling: '拉取中…',
    pull: '拉取',
    pushing: '推送中…',
    push: '推送',
    installedCount: (count: number) => `已安装（${count}）`,
    searchPlaceholder: '搜索技能…（例如 flight、docker、react）',
    search: '搜索',
    skillsCount: (count: number) => `${count} 个技能`,
    newest: '最新',
    sortByName: '按名称',
    loadingSkills: '正在加载技能…',
    noSkillsForQuery: (query: string) => `没有找到“${query}”相关技能`,
    loadSkillsFailed: '加载技能失败',
    installFailed: '安装技能失败',
    uninstallFailed: '卸载技能失败',
    updateSkillFailed: '更新技能失败',
    skillInstalled: (name: string) => `已安装技能 ${name}`,
    skillUninstalled: (name: string) => `已卸载技能 ${name}`,
    skillEnabled: (name: string) => `已启用技能 ${name}`,
    skillDisabled: (name: string) => `已禁用技能 ${name}`,
    minutesAgo: (count: number) => `${count} 分钟前`,
    hoursAgo: (count: number) => `${count} 小时前`,
    daysAgo: (count: number) => `${count} 天前`,
  },
  accountMenu: {
    accounts: '账号',
    noSavedAccounts: '还没有已保存的账号。先运行 `codex login`，然后点击重新加载。',
    account: '账号',
    active: '当前使用',
    switching: '切换中…',
    switch: '切换',
    unknown: '未知',
  },
  queued: {
    editQueuedMessage: '编辑排队消息',
    sendWithoutInterrupting: '立即发送且不打断当前工作',
    deleteQueuedMessage: '删除排队消息',
    edit: '编辑',
    steer: '引导',
    imageCount: (count: number) => count === 1 ? '1 张图片' : `${count} 张图片`,
    fileCount: (count: number) => count === 1 ? '1 个文件' : `${count} 个文件`,
    skillCount: (count: number) => count === 1 ? '1 个技能' : `${count} 个技能`,
    emptyQueuedMessage: '（空排队消息）',
  },
  rateLimit: {
    title: '额度限制',
    window: '窗口',
    leftPercent: (value: number) => `剩余 ${Math.round(value)}%`,
    usedPercent: (value: number) => `已用 ${Math.round(value)}%`,
    resettingNow: '正在重置',
    resetsIn: (value: number, unit: string) => `${value}${unit} 后重置`,
    unlimitedCredits: '无限额度',
    credits: (balance: string) => `额度 ${balance}`,
    creditsAvailable: '有可用额度',
    primaryWindow: (label: string) => `主要窗口：${label}`,
    secondaryWindow: (label: string) => `次要窗口：${label}`,
    creditsUnlimited: '额度：无限',
    creditsValue: (balance: string) => `额度：${balance}`,
  },
} as const
